### ISSUE TITLE
Vehicle_state parameter not changed on unlock

### ISSUE THREAD

**Issue by wasimeljomaa** [kappsegla/RemoteYourCar#1]
**Description:**

When trying to unlock vehicle with API, the "locked" parameter in "vehicle_state" does not change from true to false.

**Step to reproduce:**

1. Send a lock request
2. Check that "locked" parameter has changed to true.
3. Send a unlock request
4. Check that "locked" parameter has changed to false.

**Expected Results:**

"locked" parameter should change to false

**Actual Results:**

"locked" parameter has not changed to false.

**Comment by kappsegla** [comment]
This looks like a bug to me. Will have to fix this. Will probably be fixed in next release.
