### ISSUE TITLE
Same VIN-number for car 84 & 85

### ISSUE THREAD

**Issue by Magothen** [kappsegla/RemoteYourCar#14]
The same VIN-number for car 84 & 85
![bug 2](https://user-images.githubusercontent.com/71882083/137324244-09790883-b9e2-42ec-9122-25f383f9d9f5.JPG)

**To Reproduce**
1. In Postman - send a POST request for authorization (OBS! right now only valid for maria@maria.se user)
2. Send a GET request for CarID
3. Now you've got 2 cars with CarID 84 & 85 and they have the same VIN-number

**Expected behavior**
It should be 2 different VIN-numbers

**Comment by kappsegla** [comment]
It's actually the same VIN for all cars at the moment. So the fix applies to any carID. Will also fix car name and color at the same time.
