### ISSUE TITLE
New car attributes och order of cars in arraylist after restart of server 

### ISSUE THREAD

**Issue by Magothen** [kappsegla/RemoteYourCar#16]
**Changed attributes and order in arraylist after restart of server**
When the server was restarted I've got follow changes:
- order of cars in ArrayList was changed
- new VIN numbers for all my cars
- new colors for all my cars
- new names fo all my cars

**To Reproduce**
1. Restart server
2. Send new POST request for authorization
3. Send new GET requst to get carIDs

**Expected behavior**
All cars should keep theirs place in ArrayList and have the same attributes

**Screenshots**
![image](https://user-images.githubusercontent.com/71882083/139648474-6da4553d-3232-4fa7-928e-4cae1772e73d.png)

**Comment by kappsegla** [comment]
Should be fixed with 65bbaedce1e8c1039be12d58cd11d29e7b00ff7b
