### ISSUE TITLE
 set Temperature in car 1

### ISSUE THREAD

**Issue by wasimeljomaa** [kappsegla/RemoteYourCar#3]

**Comment by kappsegla** [comment]
Can we get some more information about this issue?

**Comment by shubhangi003** [comment]
Description:

- In POST request for setting the climate temp of given car id accept any value
- In Api document, value for driver_temp and passenger_temp is mandatory but while testing the given request in Postman it gives 200 OK status Code for blank values.
- In Api document it does not show any min and max value for temperature 

Test Steps

1. Add Url "https://h-178-174-162-51.a536.priv.bahnhof.se/api/1/vehicles/1/command/set_temps?driver_temp=19&passenger_temp=23" for POST request in Postman.
2. It gives 200 OK status code
3. Change the values of parameter in parameter tab for negative value (-45,-35) and click on send
4. It gives 200 OK status code  
5. In parameter tab uncheck the parameter and then send request
6.  It gives 200 OK status code

conclusion:

- As per Api document It should give status code 400 for missing parameter or values for outside of min/max range
- 
 ![ApisetmpDoc](https://user-images.githubusercontent.com/77625780/135292943-d81f419a-d3ea-42a6-b669-95016339224b.PNG)

![SetTempPlus](https://user-images.githubusercontent.com/77625780/135293080-805f6107-cb63-4a42-b03d-c5b3a330cedd.PNG)


![SetTempMinus](https://user-images.githubusercontent.com/77625780/135293252-92cfae15-895e-45a1-9ac6-578ff13046ea.PNG)

![SetTempNPara](https://user-images.githubusercontent.com/77625780/135293425-7135a1e2-23a3-4f06-a907-ad62bebc1b8e.PNG)
