### ISSUE TITLE
In Api Documentation the lock sign of authorization is unlock for lock state and vice versa

### ISSUE THREAD

**Issue by shubhangi003** [kappsegla/RemoteYourCar#5]
Description:

- In Api document, the Get request for Vehicles, Get request for drive_state and Authorize button shows Unlock sign before adding any bearer token value
- After adding Bearer key the unlock sign changes to lock

Step to reproduce:

- Go to browser "https://h-178-174-162-51.a536.priv.bahnhof.se/api/docs/"
- Check the Lock sign for Authorize Button, Get Vehicles and Get drive_state
- ![SwaDocLock](https://user-images.githubusercontent.com/77625780/135282678-192bcbb4-046e-4ee0-b09c-16959b3514f4.PNG)
- Add bearer token value and  Click on AUTHORIZE.
- ![SwaDocUloc](https://user-images.githubusercontent.com/77625780/135283118-7ece96e3-7a32-4828-9144-29785d3dc492.PNG)

Expected Results:

The locks sign should be lock before Authorization and after Adding token value sign should be changed to unlock.

Actual Results:

The locks sign is unlock before Authorization and after Adding token value the sign is changed to lock.

**Comment by kappsegla** [comment]
According to the discussion here for swagger-ui swagger-api/swagger-ui#4402 that's how swagger-ui renders the status and nothing we can change.
